version: "3"
services:
  mongodb:
    image: mongo:latest
    command: [--auth]
    container_name: springboot-mongo
    volumes:
      ['D:\\Sachin\\data\\appcode\\Spring-Docker\\spring-docker\\mongo:/data/db']
    ports:
      - 27017:27017
    networks:
      - webnet
  api: 
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8083:8083"
    container_name: springboot
    depends_on:
      - mongodb
    networks:
      - webnet
networks:
  webnet:
